import React, { useEffect, useRef } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { RxHamburgerMenu } from "react-icons/rx";
import { gsap } from "gsap";
import $ from "jquery";
import Link from "next/link";
import SplitType from 'split-type'
// const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const scrollRef = useRef(null)
  const footerRef = useRef(null)
  const heroTitle = 'Websites Apps Branding';
  const heroSubTitle = 'We make it happen';
  useEffect(() => {
    if (typeof window !== "undefined") {
      // getting elements
      const heroTitleSplitType = SplitType.create('p.hero-title')
      const heroSubTitleSplitType = SplitType.create('p.hero-subtitle')
      const detailTextSplitType = SplitType.create('p.detail-text')
      // getting elements chars
      const titleChars = heroTitleSplitType.chars;
      const subTitleChars = heroSubTitleSplitType.chars;
      const textChars = detailTextSplitType.chars;
      // ball scroll animation
      gsap.set(".ball", {xPercent: -50, yPercent: -50, zIndex: 99999});
      const ball = document.querySelector(".ball");
      const pos = { x: window.innerWidth / 2, y: window.innerHeight / 2 };
      const mouse = { x: pos.x, y: pos.y };
      const speed = 0.2;
      const xSet = gsap.quickSetter(ball, "x", "px");
      const ySet = gsap.quickSetter(ball, "y", "px");
      window.addEventListener("mousemove", e => {
        mouse.x = e.x;
        mouse.y = e.y;
      });
      gsap.ticker.add(() => {
        // adjust speed for higher refresh monitors
        const dt = 1.0 - Math.pow(1.0 - speed, gsap.ticker.deltaRatio());
        pos.x += (mouse.x - pos.x) * dt;
        pos.y += (mouse.y - pos.y) * dt;
        xSet(pos.x);
        ySet(pos.y);
      });
      // mouseenter scaling
      $(".link").on("mouseenter", function () {
        gsap.to(ball, {scale: 1.5, duration: 0.5});
      });
      $(".link").on("mouseleave", function () {
        gsap.to(ball, {scale: 1, duration: 0.5});
      });
      // heroTitle.split("").forEach((item, index) => {

      // })
      // title reveal animation
      gsap.fromTo(
        titleChars,
        {
          y: 100,
          opacity: 0
        },
        {
          y: 0,
          opacity: 1,
          stagger: 0.05,
          duration: 2,
          ease: 'power4.out',
        }
      )
      // subtitle reveal animation
      gsap.fromTo(
        subTitleChars,
        {
          y: 100,
          opacity: 0
        },
        {
          y: 0,
          opacity: 1,
          stagger: 0.05,
          duration: 0.8,
          ease: 'power4.out',
        }
      )
      // bottom text reveal animation
      gsap.fromTo(
        textChars,
        {
          y: 100,
          opacity: 0
        },
        {
          y: 0,
          opacity: 1,
          stagger: 0.05,
          duration: 1,
          ease: 'power4.out',
        }
      )
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="ball"></div>
      <header className="p-20 flex fixed top-0 right-0 left-0 justify-between items-center w-full bg-white">
        <h1 className="text-2xl link font-extrabold">
          <Link href="/" legacyBehavior>
            <a>cuberto</a>
          </Link>
        </h1>
        <div className="flex items-center justify-end gap-10">
          <h2 className="text-2xl link">
            <Link href="/our-showreel" legacyBehavior>
              <a>our showreel</a>
            </Link>
          </h2>
          <div className="hamburgerMenu flex gap-6 cursor-pointer items-center">
            <span className="text-2xl link">menu</span>
            <RxHamburgerMenu className="text-3xl link" />
          </div>
        </div>
      </header>
      <main className="container mx-auto py-20 h-full">
        <div className="flex flex-col items-start justify-center h-full mx-auto">
          <p className="hero-subtitle reveal-animate text-xl text-black overflow-hidden font-extrabold">{heroSubTitle}</p>
          <p className="hero-title reveal-animate text-9xl leading-[170px] text-black overflow-hidden font-font-Semibold">{heroTitle}</p>
        </div>
        <div className="bottom-text overflow-hidden">
          <p className="detail-text reveal-animate text-4xl text-black overflow-hidden">
            Leading digital agency with solid design and development expertise. We build readymade websites, mobile applications, and elaborate online business services.
          </p>
        </div>
      </main>
    </>
  );
}

